### ISSUE TITLE
Multiple packet forwarder instances per single helium gateway instance

### ISSUE THREAD

**Issue by pvolodin** [helium/gateway-rs#160]
It would be great to have an ability to connect multiple packet forwarder instances per single helium gateway instance.

Imagine a person owning a fistful of gateways installed at location where LTE is the only option to connect a gateway to the internet. It is economically irreasonable to run a module interacting with blockchain on the gateways. Most probably that person would prefer to install gateway-rs somewhere on a VPS (clouds, hosting provider, this doesn't much matter), take some measures to minimize packet forwarder traffic (increase stats sending period, for example), and connect the gateway's packet forwarder to the remote gateway-rs instance.

For me it seems that currently for N gateways she or he will need N gateway-rs instances. This configuration obviously will work, but it looks silly, and gives no benefits like increased security.

Ideally, gateway-rs should also be able to consume MQTT I/O from the gateways running someting licke chirpstack-gateway-bridge along with packet forwarder, this will make having data-only gateways more economically attractive.

Though the topics above seem to be more for one of HIPs than for this project in its current stage?

**Comment by madninja** [comment]
> Though the topics above seem to be more for one of HIPs than for this project in its current stage?

Indeed not quite the topic for this repo. The most common actual use case for this repo is on actual light hotspot hardware, not with the specialized cloud gateway setup. 

In general, the issue seems to infer that a single gateway-rs should be able to handle multiple packet forwarders. The problem with that approach is that the gateway has a single public key which is now pushing packets from multiple actual locations. This will have unexpected impact on how a hotspot location is perceived and witnessed, and will likely violate some PoC consensus rules. 

In order to do the right thing you'd need to have a single gateway-rs have multiple keys to represent each packet forwarder which is really not the intent of the project and has a single point of failure. Other systems are way better at managing a set of gateway-rs instances in the cloud if that's really the setup you need to run.

**Comment by pvolodin** [comment]
@madninja Thanks for the detailed explanations. I probably misinterpreted this project's goal a bit.
I'm sure Helium and the Helium's community will revisit this topic one day in the future.

**Comment by jpmeijers** [comment]
I had the same question, and want to do the same thing. I have plenty LoRaWAN gateways out in the field running mp-pkt-fwd which can forward to multiple networks using either Semtech UDP or TTNv2 MQTT. I want to configure these to forward to Helium too. On most of these gateways, like the Mikrotik ones, I can not change the firmware, so I need to run the gateway-rs on a server.

For now I opted for https://github.com/disk91/helium-gateway-rs-docker
