### ISSUE TITLE
Local gateway rarely transacts join-req/uplinks

### ISSUE THREAD

**Issue by Codepoint1** [helium/gateway-rs#287]
**Describe the bug**
Since Aug 3rd update, having specific issue with Stable Vinyl Chicken rarely responding to confirmed uplinks and join-requests from multiple (10+) local devices.  A rotating handful of adjacent gateways randomly end up "obtaining" the uplink and sending response, however many of these gateways are at the edge of reception (~ -120RSSI / -12.5SNR) so the device often misses the acknowledge and falls back into a join-state.  Stable Vinyl Chicken is on-site and has ~-60RSSI and is transacting other packets on Helium but no longer reliably obtains packets from the nearby devices.

**To Reproduce**

**Device Info (please complete the following information):**
 - Production VIP Console
 - Console Device ID: 7dc322ed-b74a-4f9b-ae31-a609dee2deff
 - Device dev eui / app eui:  B460775090000591 / B460775000000090
 - How often is device sending data:  Every 3 hours, plus whenever sensor triggered.
 - Region:  US915SB2
 - Hotspots (names) used to transfer data:  Stable Vinyl Chicken

**Additional context**
Gateway is Bobcat-300.  It has been rebooted several times, and factory-reset once.  No change in behavior.  Ota Firmware version 1.0.3.3.    Could it be that backhaul latency is high and this gateway no longer secures the packet??  However the timing of these symptoms seems correlated to the recent update.  Tried increasing the RX delay in the device profile to 2 seconds / 5 seconds with no change in end-behavior.

**Screenshots**

**Comment by lytzV** [comment]
Multiple hotspots may pick up the same packet, and only the first one that delivers the packet to the LNS will be shown on the console. Sometimes a hotspot may have really good rf stats, but it may simply be too slow when trying to deliver the packet to LNS. You could enable multi-packet config so that there is more leeway in the packet delivery process, and you can [follow the tutorial here](https://docs.helium.com/use-the-network/console/multi-packets/#multiple-packets) :)
